# Database
# spring.datasource.url=jdbc:postgresql://localhost:5432/lendme_db
# spring.datasource.username=postgres
# spring.datasource.password=iamachide
# spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver



# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=lendme_super_secret_key_minimum_32_chars_long!!
jwt.access-token-expiry=86400000
jwt.refresh-token-expiry=604800000

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Server
server.port=8080